import Foundation

class A2AClient {
    static let protocolVersion = "1.0"

    let baseURL: URL

    init(baseURL: URL) {
        self.baseURL = baseURL
    }

    /// Send a message and return streaming SSE events (A2A 1.0 SendStreamingMessage).
    /// Task ID is generated by the server and returned in the first stream event.
    func sendStreamingMessage(text: String, contextId: String? = nil) -> AsyncThrowingStream<String, Error> {
        var message: [String: Any] = [
            "messageId": UUID().uuidString,
            "role": "ROLE_USER",
            "parts": [["text": text]],
        ]
        if let contextId {
            message["contextId"] = contextId
        }
        let body: [String: Any] = [
            "jsonrpc": "2.0",
            "method": "SendStreamingMessage",
            "id": UUID().uuidString,
            "params": ["message": message],
        ]
        var req = URLRequest(url: baseURL.appendingPathComponent(""))
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue("text/event-stream", forHTTPHeaderField: "Accept")
        req.setValue(Self.protocolVersion, forHTTPHeaderField: "A2A-Version")
        req.httpBody = try? JSONSerialization.data(withJSONObject: body)
        return SSEClient.stream(request: req)
    }

    /// Fetch current task state (for re-sync after background).
    func getTask(taskId: String) async throws -> TaskStatus {
        let body: [String: Any] = [
            "jsonrpc": "2.0",
            "method": "GetTask",
            "id": UUID().uuidString,
            "params": ["id": taskId],
        ]
        var req = URLRequest(url: baseURL)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(Self.protocolVersion, forHTTPHeaderField: "A2A-Version")
        req.httpBody = try? JSONSerialization.data(withJSONObject: body)
        let (data, _) = try await URLSession.shared.data(for: req)
        let resp = try JSONDecoder().decode(JSONRPCResponse<GetTaskResult>.self, from: data)
        return resp.result.status
    }

    /// Fetch agent card from the official A2A 1.0 well-known path.
    func fetchAgentCard() async throws -> AgentCard {
        let url = baseURL
            .appendingPathComponent(".well-known")
            .appendingPathComponent("agent-card.json")
        let (data, response) = try await URLSession.shared.data(from: url)
        guard let http = response as? HTTPURLResponse,
              (200...299).contains(http.statusCode) else {
            throw URLError(.badServerResponse)
        }
        return try JSONDecoder().decode(AgentCard.self, from: data)
    }
}

private struct JSONRPCResponse<T: Decodable>: Decodable {
    let result: T
}

private struct GetTaskResult: Decodable {
    let status: TaskStatus
}
